server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: p_pao-backend
  #datasuorce
  datasource:
    password: ${spring.datasource.password}
    username: ${spring.datasource.username}
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}
  #session
  session:
    timeout: 86400
    store-type: redis
  servlet:
    multipart:
      max-file-size: 100MB
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  #redis
  redis:
    password: ${spring.redis.password}
    database: ${spring.redis.database}
    port: ${spring.redis.port}
    host: ${spring.redis.host}
mybatis-plus:
 configuration:
   map-underscore-to-camel-case: false
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
 global-config:
  db-config:
   logic-delete-field: isDelete # 默认字段名为 deleted
   logic-delete-value: 1 # 逻辑已删除值（默认为 1）
   logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
aliyun:
  oss:
    endpoint: ${aliyun.oss.endpoint}
    accessKeyId: ${aliyun.oss.accessKeyId}
    accessKeySecret: ${aliyun.oss.accessKeySecret}
    bucketName: ${aliyun.oss.bucketName}
knife4j:
  enable: true