server:
  port: 8081
spring:
  application:
    name: p_pao-backend
  #session
  session:
    timeout: 86400
    store-type: redis
  servlet:
    multipart:
      max-file-size: 100MB
  mvc:
    path match:
      matching-strategy: ant_path_matcher
mybatis-plus:
 configuration:
   map-underscore-to-camel-case: false
#   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
 global-config:
  db-config:
   logic-delete-field: isDelete # 默认字段名为 deleted
   logic-delete-value: 1 # 逻辑已删除值（默认为 1）
   logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
knife4j:
  enable: true